# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursenames',
            name='user',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='course',
        ),
        migrations.DeleteModel(
            name='Coursenames',
        ),
        migrations.DeleteModel(
            name='Descriptions',
        ),
    ]
