# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('course', '0002_auto_20161212_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='course', to='logreg.User'),
        ),
    ]
