# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='user', to='logreg.User'),
        ),
        migrations.AddField(
            model_name='location',
            name='course',
            field=models.ManyToManyField(related_name='course', to='course.Course'),
        ),
    ]
